
spring:
  application:
    name: Profiles-App
  jpa:
    show-sql: true



management:
  endpoints:
    web:
      exposure:
        include:
          '*'

  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always

info:
  contact:
    phone: 123-123-1234
    email: support@myapp.com
  copyright: 2018 My Awesome App, Inc.

greeting:
  message: Hiya
  

  
---
spring:
  profiles: production
  
greeting:
  message: HELLO FROM PRODUCTION

